---
# tasks file for docker-install

- name: Add the Docker key for installation
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add the Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Install Docker
  apt:
    name: "{{ packages }}"
    state: present
    force: yes
  vars:
    packages:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io

- name: Configure Docker daemon
  copy:
    src: ./../files/daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - docker restart

- name: Flush handlers
  meta: flush_handlers
