---
- hosts: "{{ target }}"
  become: yes
  roles:
    - common
    - swapoff
    - docker-install
    - kubernetes-install
    - kubectl-install
    - cluster-init
    - remove-master-taint
