---
- hosts: all
  become: yes
  roles:
    - common
    - swapoff
    - docker-install
    - kubernetes-install

- hosts: master_nodes
  become: yes
  roles:
    - kubectl-install
    - cluster-init
