---
- hosts: all
  become: yes
  roles:
    - common
    - docker-install
    - kubernetes-install

- hosts: master_nodes
  become: yes
  roles:
    - kubectl-install
    - cluster-init

- hosts: worker_nodes
  become: yes
  roles:
    - cluster-join
