---
# tasks file for kubernetes-install

- name: Install kubelet and kubeadm
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kubelet=1.16.1-00
      - kubeadm=1.16.1-00
