---
# handlers file for docker-install

- name: docker status
  service:
    name: docker
    state: started

- name: docker restart
  service:
    name: docker
    daemon_reload: true
    state: restarted
