---
# tasks file for cluster-init

- name: Initialize the Kubernetes cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: cluster_init_result

- debug: msg="{{ cluster_init_result.stdout_lines }}"

- name: Make kubectl work for non-admin user
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Setup kubectl config for non-admin user
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Apply Flannel to the cluster
  become: no
  command: "kubectl apply -f {{ flannel_config }}"

- name: Get join command
  shell: kubeadm token create --print-join-command
  register: join_command_result

- name: Set node join command fact
  set_fact:
    join_command: "{{ join_command_result.stdout_lines[0] }}"
  delegate_facts: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['worker_nodes'] }}"
