---
# tasks file for common

- name: Update and upgrade packages
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 86400

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
